<%@ Page Title="" Language="C#" MasterPageFile="~/AISMaster.Master" AutoEventWireup="true" CodeBehind="ForStudents.aspx.cs" Inherits="AISWebsite.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contentPlaceHolderforMain" runat="server">
    <h1 style="margin: -1px 0px 11px; padding: 0px; font-size: 20px; font-weight: bold; line-height: 23px; font-style: normal; font-family: Ubuntu, Arial, Helvetica, sans-serif; max-width: 556px; color: rgb(226, 0, 38); text-transform: uppercase; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">FOR STUDENTS</h1>
<p class="leadin" style="margin: 0px 0px 14px; padding: 0px; line-height: 19px; font-size: 16px; color: rgb(62, 62, 62); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    AIS describes itself as a multicultural family – developing friendships with people from around the world is what makes this institute unique. We have international students from the Pacific, Asia, Europe, America, India and Africa studying at undergraduate to postgraduate level.&nbsp;</p>
<p style="margin: 0px 0px 1em; padding: 0px; line-height: inherit; color: rgb(62, 62, 62); font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    To fully utilise your student experience, it is important to make the most of what AIS offers for domestic and international students. The many clubs, social, sporting and cultural events organised by Student Services enables you to mingle with a diverse range of people inside and outside the classroom.</p>
<p style="margin: 0px 0px 1em; padding: 0px; line-height: inherit; color: rgb(62, 62, 62); font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Studying can be both a rewarding and challenging experience. Student Service Officers<a href="http://www.ais.ac.nz/284/staff/" style="line-height: inherit; text-decoration: none; color: rgb(226, 0, 38);"></a><span>&nbsp;</span>and AIS tutors are available to share your successes and to give you<span>&nbsp;</span><a href="https://ais.ac.nz/for-students/support/" style="line-height: inherit; text-decoration: none; color: rgb(226, 0, 38);">support</a>&nbsp;if times are tough.</p>
<p style="margin: 0px 0px 1em; padding: 0px; line-height: inherit; color: rgb(62, 62, 62); font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Being an AIS student is a positive experience as our graduates and students will testify. Common feedback is that AIS is an institute with friendly and helpful staff and internationally reputable courses and qualifications.</p>
<p style="margin: 0px 0px 1em; padding: 0px; line-height: inherit; color: rgb(62, 62, 62); font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    For further information email<span>&nbsp;</span><a href="mailto:enquiry@ais.ac.nz" style="line-height: inherit; text-decoration: none; color: rgb(226, 0, 38);">enquiry@ais.ac.nz</a></p>
</asp:Content>
